repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: detect-private-key
      - id: detect-aws-credentials
      - id: fix-byte-order-marker
      - id: forbid-submodules
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.12.1
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - .
          - pytest
