---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: staticdev.firefox

collections:
  - name: community.general
    version: 6.3.0

  - name: sculley.mac_setup
    version: 1.2.2

  - name: ansible.posix
    version: 1.5.1