# code: language=ansible
- name: Setup home directory
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: "Install Oh My ZSH"
      ansible.builtin.shell: /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"
    - name: "Setup zprofile"
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.zprofile"
        content: |
          eval "$(ssh-agent -s)"
          case "${OSTYPE}|$(arch)" in
            darwin*|i386)
              eval "$(/usr/local/bin/brew shellenv)"
              ;;
            darwin*|aarch64)
              eval "$(/opt/homebrew/bin/brew shellenv)"
              ;;
          esac
          eval "$(direnv hook zsh)"
          eval "$(wezterm shell-completion --shell zsh)"
        mode: "0644"
    - name: "Hush the login prompt"
      ansible.builtin.copy:
        dest: "{{ lookup('env', 'HOME') }}/.hushlogin"
        mode: "0644"
        content: ""
    - name: "Configure wezterm"
      ansible.builtin.copy:
        dest: "{{ lookup('env', 'HOME') }}/.wezterm.lua"
        mode: "0644"
        content: |
          local wezterm = require 'wezterm'
          return {
            enable_scroll_bar = true,
            font = wezterm.font_with_fallback {
              "Comic Mono",
              "JetBrains Mono",
              "Noto Color Emoji",
              "Symbols Nerd Font Mono",
            },
          }
