# code: language=ansible
- name: Install MacOS Packages
  hosts: localhost
  vars_files:
    - ../secrets.enc
  become: false
  vars:
    mas_installed_apps:
      - { id: 411643860, name: "DaisyDisk (4.3.2)" }
      - { id: 937984704, name: "Amphetamine (5.2.2)" }
    # mas_uninstalled_apps:
    #   - { id: 408981434, name: "iMovie" }
    #   - { id: 409183694, name: "Keynote" }
    #   - { id: 409201541, name: "Pages" }
    #   - { id: 409203825, name: "Numbers" }
    #   - { id: 682658836, name: "GarageBand" }
    homebrew_use_brewfile: false
    homebrew_taps:
      - homebrew/core
      - homebrew/bundle
      - homebrew/cask
    homebrew_installed_packages:
      - gh
      - direnv
      - circleci
      - python@3.8
      - python@3.9
      - python@3.10
      - python@3.11
      - poetry
      - the_silver_searcher
      - zsh
    homebrew_cask_apps:
      - google-chrome
      - firefox
      - iterm2
      - tailscale
      - openvpn-connect
      - github
      - visual-studio-code
      - gpg-suite-no-mail
      - wezterm
      # TODO: broken install
      # - docker
      # - slack
      # - zoom

  roles:
    - role: geerlingguy.mac.homebrew
      when: homebrew_installed_packages or homebrew_cask_apps or homebrew_taps
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids or mas_uninstalled_apps
      tags: ['mas']
