name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create secrets
      run: |
        echo "asdf" > .vault-password.txt
        cat << EOF > secrets
        git_name: Test user
        git_email: test-user@users.noreply.github.com
        git_signingkey: XXXXXXXXXXXXXXXX
        ansible_become_password: 
        EOF

    - name: Install dependencies
      run: make setup-all
