name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Homebrew cache
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Caches/Homebrew
          ~/Library/Caches/Homebrew
        key: brew-${{ hashFiles('playbooks/osx-playbook.yml') }}
        restore-keys: brew-

    - name: Create secrets
      run: |
        echo "asdf" > .vault-password.txt
        cat << EOF > secrets
        git_name: Test user
        git_email: test-user@users.noreply.github.com
        git_signingkey: XXXXXXXXXXXXXXXX
        ansible_become_password: 
        EOF

    - name: Test macos setup
      run: make test-all

    - name: Idempotent test
      run: make test-all | grep "^PLAY RECAP \*" -A1 | grep "changed=0"